# Generated by Django 5.0 on 2023-12-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('supervisor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Супервайзер')),
                ('tel_number_supervisor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер супервайзера')),
                ('second_name', models.TextField(blank=True, null=True)),
                ('salesman', models.CharField(blank=True, max_length=20, null=True, verbose_name='Торговый Представитель')),
                ('tel_number_salesman', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Телефона торг. представителя')),
                ('tel_number_salesman_reserve', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Телефона торг. представителя(2)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
