# Generated by Django 5.0 on 2023-12-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=1)),
                ('cost_masked', models.CharField(help_text='Минимальная сумма: 10тг', max_length=9, verbose_name='Сумма:')),
                ('bonus', models.IntegerField(blank=True, default=0, null=True, verbose_name='Бонус:')),
                ('exchange', models.IntegerField(blank=True, default=0, null=True, verbose_name='Обмен:')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии:')),
                ('date', models.DateField(default=None)),
                ('confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('payment', models.CharField(choices=[('cash', 'Наличные'), ('qr', 'QR'), ('transfer', 'Kaspi Перевод')], default='cash', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sManager.supplier')),
            ],
            options={
                'verbose_name': 'Поставку',
                'verbose_name_plural': 'Поставки',
            },
        ),
    ]
