# Generated by Django 5.0 on 2023-12-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sManager.product')),
            ],
        ),
    ]
