# Generated by Django 4.2 on 2024-01-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0003_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sManager.product'),
        ),
    ]
