# Generated by Django 4.2 on 2024-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0004_alter_productimages_supply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
