# Generated by Django 5.0.7 on 2024-07-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0008_remove_profile_num_profile_image_profile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tel_number_salesman',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tel_number_salesman_reserve',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tel_number_supervisor',
        ),
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Банковский счёт'), ('mix', 'Смешанная оплата')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Торговый Представитель')),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Телефона торг. представителя')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesmen', to='sManager.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Супервайзер')),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер супервайзера')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='sManager.supplier')),
            ],
        ),
    ]
