# Generated by Django 5.0.7 on 2024-07-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0009_remove_supplier_salesman_remove_supplier_second_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='salesman',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Торговый Представитель'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='second_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supervisor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Супервайзер'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tel_number_salesman',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Телефона торг. представителя'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tel_number_salesman_reserve',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Телефона торг. представителя(2)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tel_number_supervisor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер супервайзера'),
        ),
        migrations.DeleteModel(
            name='Salesman',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
