# Generated by Django 5.0.7 on 2024-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0010_remove_supervisor_supplier_supplier_salesman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='Время публикации'),
        ),
    ]
