# Generated by Django 5.0.7 on 2024-07-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0015_client_is_chosen_alter_client_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_chosen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Избранный'),
        ),
    ]
