# Generated by Django 5.0.7 on 2024-07-27 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0021_alter_debt_description_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
