# Generated by Django 5.0.7 on 2024-07-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sManager', '0024_financerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financerecord',
            old_name='bank_amount',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='financerecord',
            old_name='deposit',
            new_name='transfer_amount',
        ),
    ]
